# 
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'

# ペースト
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# File System
[[plugins]]
repo = 'Shougo/vimfiler'

# Shell
[[plugins]]
repo = 'Shougo/vimshell'

# 括弧
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'luochen1990/rainbow'
# csv
[[plugins]]
repo = 'mechatroner/rainbow_csv'

# 画面分割の時に使うもの
[[plugins]]
repo = 'kana/vim-submode'

# 文字の入れ替え
[[plugins]]
repo = 'kana/vim-operator-replace'
[[plugins]]
repo = 'kana/vim-operator-user'


