[[plugins]]
repo = 'Shougo/dein.vim'

# vimproc: インストール後の処理も書いてる
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# よくわからないファイル
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

# 補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# File System
[[plugins]]
repo = 'Shougo/vimfiler'

# Shell
[[plugins]]
repo = 'Shougo/vimshell'
#rev = '3787e5'

# 括弧
[[plugins]]
repo = 'tpope/vim-surround'

# Coffee Script用
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'claco/jasmine.vim'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'


[[plugins]]
repo = 'thinca/vim-quickrun'

# 画面分割の時に使うもの
[[plugins]]
repo = 'kana/vim-submode'


