# 以下言語ごとの設定

# Rust lang
[[plugins]]
repo = 'racer-rust/vim-racer'
[[plugins]]
repo = 'rust-lang/rust.vim'
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']

#Javascript
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
[[plugins]]
repo = 'leafgarland/typescript-vim'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'othree/es.next.syntax.vim'
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
[[plugins]]
repo = 'ianks/vim-tsx'
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
[[plugins]]
repo = 'wavded/vim-stylus'

# mql4
[[plugins]]
repo = 'vobornik/vim-mql4'

# elm
[[plugins]]
repo = 'lambdatoast/elm.vim'

# C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# web template
[[plugins]]
repo = 'digitaltoad/vim-pug'
[[plugins]]
repo = 'statianzo/vim-jade'
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'


# latex
[[plugins]]
repo = 'lervag/vimtex'

# Flutter
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
